services:
  web-calc:
    image: nginx:latest
    networks:
      - net
    volumes:
      - './html:/usr/share/nginx/html'
  
  browser:
    image: fathyb/carbonyl:latest
    networks:
      - net

networks:
  net:

